title:   Steven Dai
logo: "/images/?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br><br>
  Passionate individual aspiring to excel in the field of data analysis, proficient in SQL, Power BI and Tableau. Eager to apply analytical skills to real-world scenarios, I am passionate about transforming data into valuable insights. Ready to leverage my skills to contribute effectively in the ever-evolving landscape of data analysis.
  <br><br><br>
  <a href="">View My LinkedIn Profile</a>
  <br><br><br>
  <a href="https://public.tableau.com/app/profile/steven.dai1737/vizzes">View My Tableau Work Samples</a>
  <br><br><br>
  <a href="https://www.notion.so/stevendai/Portfolio-Steven-Dai-01c5e680b4c34dc486e8ee6dbfa090ae">View My Notion Portfolios</a>
  
theme: jekyll-theme-minimal   
 
